version: '3'
services:

  app:
    image: ghcr.io/remast/gobuff_realworld_example_app/app:latest
    container_name: gobuf___app
    hostname: app
    ports:
      - "3000:3000"
    depends_on: 
      - db
    environment:
      - "WAIT_HOSTS=db:5432"
      - "DATABASE_HOST=db"

  db:
    image: postgres:latest
    container_name: gobuf___db
    hostname: db
    environment:
      - "POSTGRES_DB=gobuff_realworld_example_app_development"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_USER=postgres"
    ports: 
      - "5432:5432"
